### PR TITLE
Mention case problems on linux

### PR DESCRIPTION
**Pull request by UltraBlackLinux**

### CODE REVIEW

**Comment by 1darky** [comment]
Use proper operating systems like windows (or use proton atleast)

**Comment by Fesiug** [comment]
> Use proper operating systems like windows (or use proton atleast)

ru moment👎

**Comment by 1darky** [comment]
> > Use proper operating systems like windows (or use proton atleast)
> 
> ru moment👎

Sadly linux people exist everywhere i dont like them they are fat

**Comment by Fesiug** [comment]
> > > Use proper operating systems like windows (or use proton atleast)
> > 
> > ru moment👎
> 
> Sadly linux people exist everywhere i dont like them they are fat 

ru moment👎

**Comment by Fesiug** [comment]
Sadly ru people exist everywhere i dont like them they are fat

**Comment by UltraBlackLinux** [comment]
sadly- ... WTF is going on here?

**Comment by Fesiug** [comment]
I H8 Darky

**Comment by 1darky** [comment]
Why

**Pull request closed without merging**
